const fs = require('fs');

let content = fs.readFileSync('src/data/menu.ts', 'utf8');

const uniqueAppeals = {
  'Cold Coffee': 'A classic blend of chilled milk and rich espresso.',
  'Chocolate Cold Coffee': 'Cold coffee blended with rich chocolate syrup.',
  'Hazelnut Cold Coffee': 'Chilled coffee infused with smooth hazelnut flavor.',
  'Irish Cold Coffee': 'Cold coffee with a distinct, creamy Irish flavor profile.',
  'Caramel Cold Coffee': 'Chilled coffee sweetened with buttery caramel syrup.',
  'Strawberry': 'A creamy and refreshing strawberry blended shake.',
  'Mango': 'A thick and fruity shake made with sweet mangoes.',
  'Pineapple': 'A smooth shake with a tangy and tropical pineapple flavor.',
  'Blueberry': 'A rich and creamy shake blended with sweet blueberries.',
  'Vanilla': 'A classic, smooth shake made with real vanilla bean.',
  'Black Currant': 'A sweet and tangy shake with rich black currant flavor.',
  'Butterscotch': 'A creamy shake with sweet, caramelized butterscotch notes.',
  'Oreo Shake': 'A thick shake blended with crushed Oreo cookies.',
  'Kitkat Shake': 'A creamy chocolate shake mixed with crispy KitKat pieces.',
  'Brownie Shake': 'A rich shake blended with soft, chocolate fudge brownie chunks.',
  'Virgin Mojito': 'A refreshing blend of mint, lime, and sparkling soda.',
  'Lemon Iced Tea': 'Chilled black tea with a refreshing squeeze of lemon.',
  'Lemonade (Sweet/Salty/Masala)': 'Classic lemonade, customized to your preferred taste.',
  'Peach Iced Tea': 'Smooth iced tea infused with sweet peach flavor.',
  'Strawberry Mojito': 'A crisp mojito mixed with sweet strawberry flavors.',
  'Watermelon Mojito': 'A refreshing mojito blended with fresh watermelon notes.',
  'Blueberry Mojito': 'A classic mint mojito infused with sweet blueberries.',
  'Spicy Mango Mojito': 'A tropical mango mojito with a hint of warming spice.',
  'Green Apple Mojito': 'A crisp and tart mojito made with green apple flavor.',
  'Blue Lagoon': 'A refreshing and vibrant citrus-flavored sparkling cooler.',
  'Veg Patty Wrap': 'A crispy vegetable patty wrapped in a soft, warm tortilla.',
  'Mexican Wrap': 'A flavorful wrap filled with spiced beans and fresh vegetables.',
  'Paneer Wrap': 'A soft wrap filled with spiced cottage cheese and fresh greens.',
  'Veg Noodles': 'Stir-fried noodles tossed with a mix of fresh vegetables.',
  'Chilli Garlic Noodles': 'Savory noodles wok-tossed with a spicy garlic sauce.',
  'Singapore Noodles': 'Curry-flavored stir-fried noodles with mixed vegetables.',
  'Hakka Noodles': 'Classic smoky stir-fried noodles with crunchy vegetables.',
  'Chilli Potato': 'Crispy potato wedges coated in a sweet and spicy sauce.',
  'Chilli Paneer': 'Cottage cheese cubes tossed in a spicy and tangy sauce.',
  'Honey Chilli Potato': 'Crispy potatoes glazed with sweet honey and spicy chili.',
  'Chilli Mushroom': 'Fried mushrooms wok-tossed in a savory, spicy glaze.',
  'Veg Fried Rice': 'Fluffy rice stir-fried with finely chopped fresh vegetables.',
  'Paneer Fried Rice': 'Savory fried rice cooked with soft cubes of cottage cheese.',
  'Steam Veg Momos': 'Steamed dumplings filled with finely minced mixed vegetables.',
  'Steam Paneer Momos': 'Steamed dumplings filled with seasoned cottage cheese.',
  'Veg Kurkure Momos': 'Crunchy, deep-fried dumplings with a savory vegetable filling.',
  'Paneer Kurkure Momos': 'Crispy, fried dumplings stuffed with spiced cottage cheese.',
  'Veg Chilli Momos': 'Vegetable dumplings tossed in a spicy, tangy wok sauce.',
  'Paneer Chilli Momos': 'Cottage cheese dumplings coated in a fiery chili sauce.',
  'Multigrain Momos (10pcs)': 'Nutritious multigrain dumplings filled with fresh vegetables.',
  'Salted Corn': 'Sweet corn kernels lightly seasoned with salt.',
  'Peri Peri Corn': 'Sweet corn tossed in a spicy and tangy peri-peri seasoning.',
  'Cheese Baked Corn': 'Sweet corn kernels baked with a rich cheese topping.',
  'Salted Fries': 'Classic, crispy french fries lightly seasoned with salt.',
  'Peri Peri Fries': 'Crispy french fries dusted with a spicy peri-peri seasoning.',
  'Bombay Kaccha': 'A classic street-style sandwich with tangy, vibrant flavors.',
  'Vegetable Club': 'A layered club sandwich filled with crisp, fresh vegetables.',
  'Paneer Takatak': 'A toasted sandwich filled with spicy, flavorful paneer.',
  'Jam With Cheese': 'A simple, comforting sandwich with fruit jam and melted cheese.',
  'Cheese Corn': 'A toasted sandwich filled with sweet corn and melted cheese.',
  'Aloo Tikki': 'A soft bun filled with a crispy, spiced potato patty.',
  'Veg Burger': 'A classic burger with a hearty vegetable patty and fresh greens.',
  'Masala Burger': 'A flavorful burger featuring an Indian-spiced patty.',
  'Paneer Burger': 'A satisfying burger with a thick, grilled cottage cheese patty.',
  'Double Decker': 'A generous, two-tiered burger for a hearty appetite.',
  'Mixed Sauce': 'Pasta tossed in a blend of rich cream and tangy tomato sauce.',
  'Red Sauce': 'Pasta served in a classic, savory tomato and herb sauce.',
  'Pink Sauce': 'Pasta coated in a creamy, tomato-infused pink sauce.',
  'White Sauce': 'Pasta tossed in a rich, creamy, and cheesy white sauce.',
  'Classic Garlic Bread': 'Toasted bread spread with aromatic garlic and herb butter.',
  'Stuffed Garlic Bread': 'Crispy garlic bread filled with a savory, cheesy center.',
  'Paneer Garlic Bread': 'Garlic bread topped with spiced cottage cheese pieces.',
  'Kulhad Pizza': 'A unique, cheesy pizza baked in a traditional clay pot.',
  'Margherita': 'A classic pizza topped with fresh tomato sauce and mozzarella.',
  'Capsicum Delight': 'A cheesy pizza topped with crisp, fresh bell peppers.',
  'Corn Exotic': 'A savory pizza topped with sweet corn and melted cheese.',
  'Vegetable Pizza': 'A classic pizza loaded with a mix of fresh vegetables.',
  'Tandoori Pizza': 'A flavorful pizza featuring smoky, Indian-spiced toppings.',
  'Farm House': 'A hearty pizza topped with an assortment of rustic vegetables.',
  'Chef Special': 'Our signature pizza prepared with the chef’s choice of toppings.',
  'Vegetable Salad Bowl': 'A fresh, crisp mix of seasonal greens and vegetables.',
  'Paneer Salad Bowl': 'A healthy salad topped with protein-rich cottage cheese.',
  'Chef Special Salad': 'A premium mixed salad served with our signature dressing.',
  'Chocolate Brownie': 'A rich, dense, and classic chocolate fudge brownie.',
  'Choco Lava Cake': 'A soft chocolate cake with a warm, molten center.',
  'Brownie With Hot Fudge': 'A chocolate brownie served with warm, rich fudge sauce.',
  'Brownie With Ice Cream': 'A warm brownie served alongside cold vanilla ice cream.'
};

content = content.replace(/\{ id: '(.*?)', name: '(.*?)', category: '(.*?)', group: '(.*?)', price: (.*?), description: '(.*?)', image: '(.*?)', isVeg: (.*?) \}/g, (match, id, name, category, group, price, oldDesc, image, isVeg) => {
  const itemAppeal = uniqueAppeals[name] || uniqueAppeals[name.replace(/\\'/g, "'")] || 'A professionally crafted dish to satisfy your cravings.';
  return `{ id: '${id}', name: '${name}', category: '${category}', group: '${group}', price: ${price}, description: '${itemAppeal.replace(/'/g, "\\'")}', image: '${image}', isVeg: ${isVeg} }`;
});

fs.writeFileSync('src/data/menu.ts', content);
