const fs = require('fs');

let content = fs.readFileSync('src/data/menu.ts', 'utf8');

const uniqueAppeals = {
  'Cold Coffee': 'A refreshing, icy blast of classic espresso to instantly revitalize you.',
  'Chocolate Cold Coffee': 'Rich cocoa bliss swirled seamlessly into a frosty, caffeinated treat.',
  'Hazelnut Cold Coffee': 'Nutty, roasted hazelnut notes perfectly balancing the chill of icy coffee.',
  'Irish Cold Coffee': 'A decadent, creamy delight infused with bold Irish cream essence.',
  'Caramel Cold Coffee': 'Sweet, buttery caramel drizzles meeting the intense kiss of cold brew.',
  'Strawberry': 'A luscious, pastel-pink dream bursting with fresh strawberry sweetness.',
  'Mango': 'Tropical sunshine in a glass, delightfully thick and intensely fruity.',
  'Pineapple': 'A tangy, tropical escape blended into a smooth, creamy masterpiece.',
  'Blueberry': 'Vibrant berry goodness offering a perfect balance of tart and sweet.',
  'Vanilla': 'Classic, velvety smooth, and speckled with real, aromatic vanilla bean.',
  'Black Currant': 'A bold, tangy berry blend that is refreshingly rich and velvety.',
  'Butterscotch': 'Crunchy caramelized bits floating in a perfectly creamy, sweet shake.',
  'Oreo Shake': 'A cookie-lover’s fantasy, loaded with crushed Oreos and thick cream.',
  'Kitkat Shake': 'Crispy wafer crumbles perfectly submerged in a rich chocolate blend.',
  'Brownie Shake': 'Fudgy, gooey brownie chunks transformed into the ultimate thick shake.',
  'Virgin Mojito': 'A zesty, minty splash of pure refreshment on a warm, lazy day.',
  'Lemon Iced Tea': 'Brisk, cool tea perfectly elevated by a tangy squeeze of fresh lemon.',
  'Lemonade (Sweet/Salty/Masala)': 'Your classic thirst quencher, customizable to your exact flavor craving.',
  'Peach Iced Tea': 'A subtly sweet, fruity infusion that is both crisp and delightfully calm.',
  'Strawberry Mojito': 'A bubbly, minty delight kissed with the sweet essence of ripe strawberries.',
  'Watermelon Mojito': 'Juicy, summery watermelon notes mixed with cool mint and sparkling soda.',
  'Blueberry Mojito': 'A vibrantly purple, berry-infused twist on the classic minty cooler.',
  'Spicy Mango Mojito': 'A tantalizing kick of spice meeting the sweet embrace of tropical mango.',
  'Green Apple Mojito': 'A tart, crisp, and brilliantly green splash of pure fruity refreshment.',
  'Blue Lagoon': 'A mesmerizing, vibrant blue citrus cooler that perfectly chills your senses.',
  'Veg Patty Wrap': 'A crispy, golden vegetable patty hugged snugly by a soft, warm tortilla.',
  'Mexican Wrap': 'A fiesta of spices, beans, and fresh veggies rolled into one hearty bite.',
  'Paneer Wrap': 'Succulent, spiced cottage cheese cubes nestled in a fresh, wholesome wrap.',
  'Veg Noodles': 'Sizzling, wok-tossed strands packed with crunchy, vibrant garden vegetables.',
  'Chilli Garlic Noodles': 'An addictive, garlicky kick elevating these perfectly stir-fried noodles.',
  'Singapore Noodles': 'A fragrant, curry-infused delight offering a taste of Asian street food.',
  'Hakka Noodles': 'Classic, smoky, and delightfully savory wok-tossed noodle perfection.',
  'Chilli Potato': 'Crispy potato wedges bathed in a sticky, sweet, and fiery glaze.',
  'Chilli Paneer': 'Soft cottage cheese cubes tossed in a bold, spicy, and tangy wok sauce.',
  'Honey Chilli Potato': 'The perfect harmony of sweet honey and fiery chilli over crispy spuds.',
  'Chilli Mushroom': 'Earthy, plump mushrooms wok-fried to a spicy, tantalizing finish.',
  'Veg Fried Rice': 'Light, fluffy grains tossed with an aromatic medley of fresh, crunchy veg.',
  'Paneer Fried Rice': 'Savory, smoky rice studded with soft, flavorful cubes of cottage cheese.',
  'Steam Veg Momos': 'Delicate, translucent dumplings hiding a savory, finely minced veg core.',
  'Steam Paneer Momos': 'Soft, steamed parcels filled with seasoned, melt-in-your-mouth paneer.',
  'Veg Kurkure Momos': 'An unbelievable crunch giving way to a savory, juicy vegetable filling.',
  'Paneer Kurkure Momos': 'Golden, extra-crispy exterior hiding a warm, soft, and spicy paneer center.',
  'Veg Chilli Momos': 'Juicy dumplings tossed in a fiercely flavorful, spicy wok sauce.',
  'Paneer Chilli Momos': 'Soft paneer-filled momos elevated by a tangy, fiery chilli glaze.',
  'Multigrain Momos (10pcs)': 'A wholesome, nutritious twist on your favorite savory steamed dumplings.',
  'Salted Corn': 'Simple, sweet, and buttery corn kernels dusted with the perfect pinch of salt.',
  'Peri Peri Corn': 'Sweet, juicy corn tossed in a fiery, tangy peri-peri seasoning.',
  'Cheese Baked Corn': 'A warm, gooey, and cheesy blanket covering sweet, golden corn kernels.',
  'Salted Fries': 'The timeless classic: crispy on the outside, fluffy inside, perfectly salted.',
  'Peri Peri Fries': 'Golden, crispy fries aggressively dusted with a zesty, spicy peri-peri rub.',
  'Bombay Kaccha': 'A nostalgic, street-style sandwich bursting with tangy, vibrant local flavors.',
  'Vegetable Club': 'A towering, multi-layered classic packed with fresh, crisp garden veggies.',
  'Paneer Takatak': 'Spicy, tangy, and incredibly flavorful paneer stuffed in a toasted sandwich.',
  'Jam With Cheese': 'The perfect sweet-and-savory duet of fruity jam and gooey melted cheese.',
  'Cheese Corn': 'A creamy, cheesy delight studded with sweet corn in every toasty bite.',
  'Aloo Tikki': 'A spiced, crispy potato patty bringing classic Indian flavors to a soft bun.',
  'Veg Burger': 'A hearty, wholesome vegetable patty topped with fresh, crunchy greens.',
  'Masala Burger': 'An Indian-spiced sensation offering a flavor explosion in every mouthful.',
  'Paneer Burger': 'A thick, juicy paneer slab grilled to perfection and layered with fresh sauces.',
  'Double Decker': 'A colossal, towering feast guaranteed to conquer the most serious cravings.',
  'Mixed Sauce': 'The best of both worlds: creamy richness meeting tangy tomato vibrance.',
  'Red Sauce': 'A robust, tangy tomato base loaded with classic Italian herbs and spices.',
  'Pink Sauce': 'A velvety, luxurious blend of creamy white and zesty red sauces.',
  'White Sauce': 'An indulgently creamy, cheesy, and garlicky blanket over perfect pasta.',
  'Classic Garlic Bread': 'Warm, toasty, and generously smothered in aromatic garlic butter.',
  'Stuffed Garlic Bread': 'A savory surprise inside, wrapped in a perfectly crisp, garlicky crust.',
  'Paneer Garlic Bread': 'Spiced paneer bits adding a rich, hearty twist to classic garlic bread.',
  'Kulhad Pizza': 'A rustic, earthy experience of hot, cheesy pizza baked in a clay pot.',
  'Margherita': 'The timeless classic: simple, cheesy, and bursting with fresh tomato flavor.',
  'Capsicum Delight': 'Crunchy, fresh bell peppers adding a vibrant zest to gooey, hot cheese.',
  'Corn Exotic': 'Sweet, golden corn kernels bringing a delightful pop to a savory pizza crust.',
  'Vegetable Pizza': 'A colorful, garden-fresh medley generously scattered over a cheesy base.',
  'Tandoori Pizza': 'A smoky, spiced Indian twist on a beloved Italian classic.',
  'Farm House': 'Loaded with an abundance of fresh, rustic vegetables and stringy cheese.',
  'Chef Special': 'Our signature culinary masterpiece, loaded with the chef’s secret toppings.',
  'Vegetable Salad Bowl': 'A vibrant, crisp, and refreshing medley of nature’s best greens.',
  'Paneer Salad Bowl': 'Protein-packed paneer cubes tossed gracefully with fresh, crisp veggies.',
  'Chef Special Salad': 'A curated, premium blend of exquisite greens and a signature zesty dressing.',
  'Chocolate Brownie': 'Dense, fudgy, and intensely chocolaty—a true comfort classic.',
  'Choco Lava Cake': 'A soft cake exterior revealing a mesmerizing, molten chocolate center.',
  'Brownie With Hot Fudge': 'A warm brownie elevated by a decadent cascade of thick, hot fudge.',
  'Brownie With Ice Cream': 'The perfect contrast of a warm, gooey brownie and cold, creamy vanilla.'
};

content = content.replace(/\{ id: '(.*?)', name: '(.*?)', category: '(.*?)', group: '(.*?)', price: (.*?), description: '(.*?)', image: '(.*?)', isVeg: (.*?) \}/g, (match, id, name, category, group, price, oldDesc, image, isVeg) => {
  const itemAppeal = uniqueAppeals[name] || uniqueAppeals[name.replace(/\\'/g, "'")] || 'A beautifully crafted culinary delight guaranteed to satisfy your palate.';
  return `{ id: '${id}', name: '${name}', category: '${category}', group: '${group}', price: ${price}, description: '${itemAppeal.replace(/'/g, "\\'")}', image: '${image}', isVeg: ${isVeg} }`;
});

fs.writeFileSync('src/data/menu.ts', content);
